# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  push:
    tags:
      - "*"

defaults:
  run:
    shell: bash

jobs:
  Publish:
    runs-on: "ubuntu-latest"

    permissions:
      contents: read
      id-token: write # Required for OIDC

    steps:
      - name: "📥 Checkout"
        uses: actions/checkout@v4

      - name: "🗃️ Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org

      - name: "📐 Install dependencies"
        run: npm ci

      - name: "🖌️ Lint"
        run: npm run lint

      - name: "🧪 Test"
        run: npm run test

      - name: "📖 Retrieve package information"
        uses: geekyeggo/npm-pkg@v1
        id: pkg

      - name: "📤 Publish"
        run: npm publish --tag ${{ steps.pkg.outputs.version-tag }}
